name: ARM64 Release

on:
  pull_request:
  push:
    branches:
      - master
      - stable
      - rc/**
      - all
    tags:
      - '**'
  workflow_dispatch:

jobs:
  arm64:
    name: Publish bindist
    runs-on: [self-hosted, linux, ARM64]
    steps:
      - name: Clone project
        uses: actions/checkout@v2
      - shell: bash
        run: |
          set -ex

          docker build . -f etc/dockerfiles/arm64.Dockerfile -t stack --build-arg USERID=$(id -u) --build-arg GROUPID=$(id -g)
          rm -rf _release
          mkdir -p _release
          docker run --rm -v $(pwd):/src -w /src stack bash -c "/home/stack/release build"

      - name: Upload bindist
        uses: actions/upload-artifact@v2
        with:
          name: Linux-ARM64
          path: _release/stack-*
